
source:
  type: "csv"               
  path: "data/source.csv"   
  
  db_connection:           
    dialect: "postgresql"
    host: "localhost"
    port: 5432
    database: "your_db"
    username: "your_user"
    password: "your_pass"
    table: "your_table"
  
  koboltool:
    api:

  googlesheet:
    endpoint:

arcgis:
  username: "your_agol_user"
  password: "your_agol_password"
  layer_name: "Your_Feature_Layer"
  folder: "ETL Layers"      # optional
  spatial_reference: 4326   # WKID
  geometry_type: "point"    # point, polyline, polygon
  fields:
    - name: "name"
      type: "esriFieldTypeString"
    - name: "latitude"
      type: "esriFieldTypeDouble"
    - name: "longitude"
      type: "esriFieldTypeDouble"


